# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d25349cf795e78c334161b96b4147d720219d29c8b090bc548763b58a369ca3901c0eacabb94b9728b9bf267fa30dd0581a888f7524e96fef88da0ae22414ba

test:
  secret_key_base: b8e170bcc3774fac4f94bcff68bd4bf1be53fc2a96c0f0b97252a0b22626ee86453f9531f400d78a49e20eb448e356520f8960f465b2ec3594aa6c3aa3203432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
